name: fleasytier
description: A Flutter GUI for EasyTier mesh VPN.
publish_to: 'none'
version: 1.2.6

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  window_manager: ^0.4.3
  tray_manager: ^0.5.2
  toml: ^0.16.0
  file_picker: ^10.3.10
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.1
  font_awesome_flutter: 10.8.0
  windows_single_instance: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.ico
    - assets/tray_icon.png
